name: Auxiliary

on:
  push: {}
  status: {}
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@config-path
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
