name: Merge Pal (PR)

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  test-this:
    runs-on: ubuntu-latest
    steps:
      - run: echo "All ok"
  test-that:
    runs-on: ubuntu-latest
    steps:
      - run: echo "All ok"
  mergepal-merge:
    runs-on: ubuntu-latest
    needs:
      # make sure all required jobs are listed here
      - test-this
      - test-that
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@labels
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
