name: Review

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }} "
  mergepal:
    runs-on: ubuntu-latest
    needs:
      # make sure all required jobs are listed here
      - test1-this
      - test1-that
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@on-review
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
