name: Review

on:
  status: {}
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event) }}"
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@labels
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
